name: Linux Remote Desktop

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max runtime: 6 hours

    steps:
    - name: Update and Install xRDP with Xfce4 (Lightweight)
      run: |
        sudo apt update -y
        sudo apt install -y xrdp xfce4 xfce4-goodies
        echo "xfce4-session" > ~/.xsession
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
      shell: bash

    - name: Create User MARIO
      run: |
        sudo useradd -m -s /bin/bash MARIO
        echo 'MARIO:P@ssw0rd!' | sudo chpasswd
        sudo usermod -aG sudo MARIO
        echo "xfce4-session" | sudo tee -a /home/MARIO/.xsession
        sudo chown MARIO:MARIO /home/MARIO/.xsession
      shell: bash

    - name: Install ngrok
      run: |
        curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        chmod +x ngrok
      shell: bash

    - name: Authenticate ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      shell: bash

    - name: Start ngrok Tunnel (RDP on Port 3389)
      run: ./ngrok tcp 3389 > /dev/null &
      shell: bash

    - name: Display ngrok Public Address
      run: sleep 10 && curl -s http://localhost:4040/api/tunnels
      shell: bash

    - name: Keep Session Alive for 5 Hours
      run: sleep 18000
      shell: bash
